# pyproject.toml (extract)
[project]
name = "listen-docs"
version = "0.0.1"

[project.dependencies]
fastapi      = "^0.111"
uvicorn      = {extras=["standard"], version="^0.30"}
pydantic     = "^2.7"
pdfplumber   = "^0.11"   
python-docx  = "^1.1"
python-magic = "^0.4"    